### 변수 정의

##### variable만 적으면 가장 마지막  content만 보여주고 print로 실행하면 모든 content를 보여줌
    int: 정수/ float: 소수

In [1]:
a=1

In [2]:
type(a)

int

In [17]:
a = 1; print(type(a))

<class 'int'>


In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


dict는 { }안에 표현해야 하고, 반드시 pair로 입력해야함. 

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


### Type
    str(string): a='123'의 형태.
    list: a=[1,2,3,]의 형태.
    *a[-1][0]와 같이 list 속의 list를 불러오는 것도 가능

2*3 행렬

In [2]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

##### import: 하드디스크에 다운 받아놓은 것을 메모리에 올리는 과정이라고 생각.
    anaconda 파일에 있는 numpy 파일을 불러오는 과정.
    numpy.array: numpy안에 있는 array라는 함수를 불러옴. 반드시 numpy.array 형식으로 써야 함.
    array는 matrix와 유사한 역할. 형태가 행렬같이 생긴 것. 실제로 2*3 행렬끼리의 곱은 불가능하지만 array는 가능한 것으로 미루어 완전한 행렬은 아님

In [3]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


##### error
    : (2*3) 끼리의 행렬의 곱은 불가능

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

##### T: Transpose
    (2*3) 행렬을 (3*2) 행렬로 변경해 줌.

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

In [4]:
s= 'abcdef'

In [5]:
type(s)

str

##### class: 한 기능에 따라오는 함수

In [6]:
print(type(s))

<class 'str'>
